# Generated by Django 6.0.2 on 2026-04-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0002_college_course_faculty_marksheet_role_student_subject_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energySource', models.CharField(max_length=50)),
                ('productionUnit', models.CharField(max_length=30)),
                ('outputLevel', models.CharField(max_length=50)),
                ('efficiencyRate', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_energy',
            },
        ),
    ]
