# Generated by Django 6.0.2 on 2026-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0003_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='efficiencyRate',
            field=models.CharField(max_length=20),
        ),
    ]
