# Generated by Django 6.0.2 on 2026-05-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0004_alter_energy_efficiencyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicCode', models.CharField(max_length=30)),
                ('topicName', models.CharField(max_length=50)),
                ('partitions', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'sos_topic',
            },
        ),
    ]
