# Generated by Django 6.0.2 on 2026-05-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0005_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightCode', models.CharField(max_length=30)),
                ('roomName', models.CharField(max_length=30)),
                ('brightnessLevel', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_light',
            },
        ),
    ]
