# Generated by Django 6.0.2 on 2026-05-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0006_light'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcastCode', models.CharField(max_length=30)),
                ('podcastTitle', models.CharField(max_length=30)),
                ('hostName', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_podcast',
            },
        ),
    ]
