# Generated by Django 6.0.2 on 2026-05-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0007_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=30)),
                ('receiverName', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('deliveryDate', models.DateField(max_length=15)),
            ],
            options={
                'db_table': 'sos_courier',
            },
        ),
    ]
