# Generated by Django 6.0.2 on 2026-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0008_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestName', models.CharField(max_length=30)),
                ('roomType', models.CharField(max_length=30)),
                ('checkInDate', models.DateField(max_length=15)),
                ('totalBill', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_hotel',
            },
        ),
    ]
