# Generated by Django 6.0.2 on 2026-05-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0009_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=30)),
                ('fileSize', models.CharField(max_length=30)),
                ('uploadDate', models.DateField(max_length=15)),
                ('storageType', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_cloud',
            },
        ),
    ]
