# Generated by Django 6.0.2 on 2026-05-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0010_cloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=30)),
                ('carModel', models.CharField(max_length=40)),
                ('rentPerDay', models.CharField(max_length=30)),
                ('fuelType', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'sos_car',
            },
        ),
    ]
