# Generated by Django 6.0.2 on 2026-06-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0011_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimNumber', models.CharField(max_length=30)),
                ('claimAmount', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_claim',
            },
        ),
    ]
