# Generated by Django 6.0.2 on 2026-06-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0012_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claimAmount',
            field=models.IntegerField(),
        ),
    ]
