# Generated by Django 6.0.2 on 2026-06-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0013_alter_claim_claimamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoName', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('visibility', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_repository',
            },
        ),
    ]
