# Generated by Django 6.0.2 on 2026-06-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0014_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenID', models.CharField(max_length=30)),
                ('complaintType', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_complaint',
            },
        ),
    ]
