# Generated by Django 6.0.2 on 2026-06-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0015_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantName', models.CharField(max_length=35)),
                ('companyName', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=30)),
                ('applicationStatus', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'sos_job',
            },
        ),
    ]
